"""add_sync_jobs_table

Revision ID: 38494b84ec8f
Revises: 
Create Date: 2026-06-02 12:03:47.775825
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '38494b84ec8f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_job_id'), 'sync_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_sync_jobs_source_id'), 'sync_jobs', ['source_id'], unique=False)
    # eticaret_satis is managed by the ingestion pipeline, not Alembic — do not drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_jobs_source_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_job_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###
